// settings.gradle
pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.name = "Loxposed"

include ':Loxposed Manager'
include ':Loxposed Meta Loader'
include ':Loxposed Patch Loader'
include ':Loxposed Proxy App Factory'