pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}

dependencyResolutionManagement {
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.name = "Loxposed"

include ':Loxposed Manager'
include ':Loxposed Meta Loader'
//include ':Loxposed Patch Loader'
//include ':Loxposed Proxy App Factory'