apply plugin: 'com.android.application'

android {
    namespace = 'nea.lox.metaloader'
    compileSdkVersion 21
    buildToolsVersion "21.1.0"

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
}
